export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLISTS : "SET_PLAYLISTS",
    SET_USER : "SET_USER",
    SET_TOP_TRACKS_ITEMS : "SET_TOP_TRACKS_ITEMS",
    SET_CURRENT_PLAYING_TRACK : "SET_CURRENT_PLAYING_TRACK",
    SET_RECENTLY_PLAYED_TRACK : "SET_RECENTLY_PLAYED_TRACK",
};